[colors.bright]
black = "0x797979"
blue = "0x7187a9"
cyan = "0x86d3ce"
green = "0xd4f199"
magenta = "0xa0839f"
red = "0xdd6343"
white = "0xf7f7f7"
yellow = "0xd3a75e"

[colors.cursor]
cursor = "0xd9d9d9"
text = "0x2c2c2c"

[colors.dim]
black = "0x232323"
blue = "0x556b79"
cyan = "0x5c8482"
green = "0x5e6547"
magenta = "0x6e4962"
red = "0x74423f"
white = "0x828282"
yellow = "0x8b7653"

[colors.normal]
black = "0x1c1c1c"
blue = "0x7187a9"
cyan = "0x89b1ae"
green = "0x8b9e63"
magenta = "0xa0839f"
red = "0xdd6343"
white = "0xcacaca"
yellow = "0xa26f35"

[colors.primary]
background = "0x2c2c2c"
bright_foreground = "0xd9d9d9"
dim_foreground = "0xdbdbdb"
foreground = "0xd6d6d6"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MonoLisa"
style = "Regular"

[font.offset]
y = 0

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000]"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000-"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000w"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000l"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000h"
key = "H"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000n"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000L"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0000H"
key = "H"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_title = false
opacity = 0.95
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0
