#!/bin/bash
curl -s -b $(op item get --vault Acronis 'Acronis Passport Cookie' --fields notesPlain 2>/dev/null) --request POST https://hastebin.acronis.work/documents --header "content-type: text/plain" --data-binary @- | jq -r '"https://hastebin.acronis.work/raw/\(.key)"' | tee >(pbcopy)

