#!/bin/bash

BW_PATH=$(which bw)
BW_EMAIL="roman.charugin@acronis.com"
BW_PASSWORD_KEYCHAIN_NAME="Bitwarden Password"

export BW_PASSWORD=$(security find-generic-password -a "$BW_EMAIL" -s "$BW_PASSWORD_KEYCHAIN_NAME" -w)
export BW_SESSION=$($BW_PATH unlock --raw --passwordenv BW_PASSWORD 2>/dev/null)

$BW_PATH $@ 2>/dev/null
