# LazyGit configuration
# Docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  border: rounded
  showRandomTip: false
  showCommandLog: false
  commandLogSize: 0
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#e4b567"
      - bold
    inactiveBorderColor:
      - "#4e5057"
    searchingActiveBorderColor:
      - "#f0c674"
      - bold
    optionsTextColor:
      - "#f0c674"
    selectedLineBgColor:
      - "#4a3a18"
    defaultFgColor:
      - "#c0c4c8"
